### ISSUE TITLE
cloud 的客户端，对已经加入的k8s 集群进行存活检查

### ISSUE THREAD

**Issue by caoyingjunz** [caoyingjunz/gopixiu#146]

**Comment by tenqaz** [comment]
试试

1. 定时获取所有客户端的状态，如果有变化则更新到clouds表中
2. 页面调用cloud list接口时，获取客户端的当前状态返回。

**Comment by chenghongxi** [comment]
实现一个探针，去定时检查k8s集群是不是还活着，要是连接挂了，就更新集群状态，让页面能感知到集群的异常
